Prevent TypeCatalogueInstanceProvider from throwing a first chance MissingMethodException instantiating DefaultEnumerableValueFormatter
FakeItEasy/FakeItEasy pull request #1791
Opened 2020-08-31 14:22 UTC by akrock

- Exclude FIE Assembly from TypeCatalogue
- Adjust CanBeInstantiatedAs to include checking for a public no-arg constructor.

All the tests were passing on .NET Core, I had issues w/ getting the full framework to run on my machine due to missing very old framework versions.

2020-08-31 14:23 UTC, akrock commented
Addresses #1790

2020-08-31 14:51 UTC, akrock commented
Oops forgot all the niceties of .net land that have come over the years, will fix the Array.Empty error.

2020-08-31 16:14 UTC, thomaslevesque requested changes
Thanks @akrock! I have a few minor comments (some inline in the diff, and some here).

In the issue, @blairconrad said this:

> we'd need to explicitly supply StringDummyFactory to the DynamicDummyFactory)

I think this should be changed in RootModule.cs. In fact, I'm a bit surprised that it doesn't break a test...

Also, you still have a [build error](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/builds/34946072/job/yoccfefrci5a6e2l#L52). This is because in .NET Standard 1.6, `TypeInfo` doesn't inherit from `Type`, so you can't call `HasDefaultConstructor` on it. Changing `typeInfo.HasDefaultConstructor()` to `type.HasDefaultConstructor()` should fix it

2020-08-31 16:32 UTC, thomaslevesque commented
> In fact, I'm a bit surprised that it doesn't break a test...

Ah, I see. `StringDummyFactory` was [introduced as an optimization](https://github.com/FakeItEasy/FakeItEasy/pull/1439). It works without it, it's just inefficient.

2020-08-31 17:00 UTC, blairconrad commented
> Ah, I see. `StringDummyFactory` was [introduced as an optimization](https://github.com/FakeItEasy/FakeItEasy/pull/1439). It works without it, it's just inefficient.

Oh. I thought without it we might also have a first chance exception. I could be wrong. Either way, it'd be nice to keep this.

2020-08-31 17:56 UTC, akrock commented
@thomaslevesque @blairconrad 

I explicitly added the `StringDummyFactory` in `RootModule` to the collection of `IDummyFactory` that is discovered through the `TypeCatalogue`... is this what you had in mind?

2020-08-31 21:04 UTC, akrock commented on src/FakeItEasy/TypeExtensions.cs
> +            return type.GetConstructor(Type.EmptyTypes) != null;
That is a new one to me, TIL that I have been doing it "wrong" all these years.

2020-09-01 07:12 UTC, thomaslevesque commented
> I considered asking for a change in `scanning-for-extension-points.md`, removing "its own assembly", but then I thought we might as well leave it. FakeItEasy is just doing a different _kind_ of search. A manual one. @thomaslevesque , if you disagree, I don't _mind_ if the bullet point goes away. Honestly, I think the behaviour is transparent to clients either way.

I don't mind leaving it as is

2020-09-01 07:16 UTC, thomaslevesque approved these changes
Looks good to me, thanks @akrock!
Could you please squash the commits before we merge?

2020-09-01 18:13 UTC, akrock commented
Squashed.

Thanks to you two for the great work you do on this project @thomaslevesque & @blairconrad

2020-09-01 19:55 UTC, thomaslevesque approved these changes

2020-09-01 19:55 UTC, merged

2020-09-01 19:56 UTC, thomaslevesque commented
Thanks again, @akrock !

2020-09-01 20:24 UTC, blairconrad commented
Indeed, thanks for your work, @akrock!