[WIP] Better extension point scanning
FakeItEasy/FakeItEasy pull request #1813
Opened 2021-01-07 22:47 UTC by thomaslevesque

As discussed in chat with @blairconrad

WIP because I still need to implement "light loading" of assemblies for TFMs that don't have `ReflectionOnlyLoad`.

2021-01-09 04:10 UTC, blairconrad requested changes
As usual, very nice. I like the unwrapping of the LINQ.
My biggest concern is the docs, but I have some additional minor questions and comments.

2021-01-09 22:54 UTC, thomaslevesque commented on docs/scanning-for-extension-points.md
> +* assemblies referenced by already loaded assemblies and
> assemblies already loaded in the current AppDomain that reference FakeItEasy

Yes, I thought about that, but it was already true before, and the docs didn't mention it. Anyway, assemblies that don't reference FakeItEasy can't implement extension points.

> My concern is that there's a currently-loaded assembly that _does not itself reference FIE, but that references an assembly that does and that contains an extension point class_.
> It seems unlikely to happen, but I think it's possible, and if so, we will not find that class. I'm okay not finding it, but figure we should at least write it down.

That's a good point. I'll clarify the docs

2021-01-09 22:54 UTC, thomaslevesque commented on src/FakeItEasy/Core/TypeCatalogue.cs
> +                        assembliesToScan.Add(referencedAssembly);
Good point

> or equivalently enrolling line 93 into the if on line 94

I think that's the best approach

2021-01-09 22:54 UTC, thomaslevesque commented on src/FakeItEasy/Core/TypeCatalogue.cs
> +            return true;
I like it. In fact, I probably would have written it like this, but that code was initially doing other things, which I removed when I got rid of `ReflectionOnlyLoad`, and I forgot to refactor.

2021-01-09 23:03 UTC, thomaslevesque commented
Pushed fixup commits with the suggested changes

2021-01-10 00:48 UTC, blairconrad commented on src/FakeItEasy/Core/TypeCatalogue.cs
> +                        assembliesToScan.Add(referencedAssembly);
Me too.

2021-01-10 00:49 UTC, blairconrad approved these changes
Wunderbar. Thanks!

2021-01-10 00:54 UTC, thomaslevesque commented
Squashed

2021-01-10 01:07 UTC, blairconrad approved these changes

2021-01-10 01:07 UTC, merged

2021-01-10 01:08 UTC, blairconrad commented
Thanks, @thomaslevesque! I know of at least one loyal user that will be thrilled with the change.

2021-01-10 01:10 UTC, thomaslevesque commented
Thanks for the suggestions and merge!

> I know of at least one loyal user that will be thrilled with the change.

Oh? I wonder who 🤔

2021-03-15 11:12 UTC, blairconrad commented
This change has also been released as part of [FakeItEasy 7.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/7.0.0).