Add CollectionOfFake overloads that accept an action that uses fake number to configure fake
FakeItEasy/FakeItEasy pull request #1844
Opened 2021-05-28 18:05 UTC by PiotrKlecha

Fixes #1838

2021-05-29 02:28 UTC, blairconrad reviewed
Thanks, @PiotrKlecha. Liked pretty much everything. The one request I was on the verge of making was to have the docs describe what the `int` was in the `Func` in the new overloads. Then I decided to push a commit myself. I hope this doesn't offend. The reasons I went this route were twofold

1. I noticed some other "deficiencies" in the docs around the optionBuilders, which you'd conscientiously replicated, and
2. for some reason, the GitHub/Appveyor system didn't build your PR, and I figured adding a new commit would encourage them.

If you're unhappy with my commit, please drop it. And @thomaslevesque, as usual, if _you're_ unhappy, tell me!

2021-05-29 15:28 UTC, thomaslevesque requested changes
Thanks @PiotrKlecha, this looks very good to me.
My only issue is the fact that the index start at 1. I think it would be less surprising to the user if it started at 0, like all indices. @blairconrad what do you think?

2021-05-29 15:28 UTC, thomaslevesque commented on src/FakeItEasy/A.cs
> +            return Enumerable.Range(1, numberOfFakes).Select(i => Fake<T>(options => optionsBuilder(options, i))).ToList();
Why start at index 1? That's pretty unusual...

2021-05-29 15:50 UTC, blairconrad commented
I didn't mind, but now you mention it, having 1 passed in and then needing
to access as 0 might be confusing. Probably best to change to 0. In this
case my commit'll need to be updated as well.

On Sat, May 29, 2021, 11:28 Thomas Levesque, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks @PiotrKlecha <https://github.com/PiotrKlecha>, this looks very
> good to me.
> My only issue is the fact that the index start at 1. I think it would be
> less surprising to the user if it started at 0, like all indices.
> @blairconrad <https://github.com/blairconrad> what do you think?
> ------------------------------
>
> In src/FakeItEasy/A.cs
> <https://github.com/FakeItEasy/FakeItEasy/pull/1844#discussion_r641950998>
> :
>
> > @@ -71,7 +71,20 @@ public static class A
>          [SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Justification = "This is by design when using the Expression-, Action- and Func-types.")]
>          public static IList<T> CollectionOfFake<T>(int numberOfFakes, Action<IFakeOptions<T>> optionsBuilder) where T : class
>          {
> -            return Enumerable.Range(0, numberOfFakes).Select(_ => Fake(optionsBuilder)).ToList();
> +            return CollectionOfFake<T>(numberOfFakes, (options, i) => optionsBuilder(options));
> +        }
> +
> +        /// <summary>
> +        /// Creates a collection of fakes of the specified type.
> +        /// </summary>
> +        /// <typeparam name="T">The type of fakes to create.</typeparam>
> +        /// <param name="numberOfFakes">The number of fakes in the collection.</param>
> +        /// <param name="optionsBuilder">A lambda where options for the built fake object can be specified.</param>
> +        /// <returns>A collection of fake objects of the specified type.</returns>
> +        public static IList<T> CollectionOfFake<T>(int numberOfFakes, Action<IFakeOptions<T>, int> optionsBuilder)
> +            where T : class
> +        {
> +            return Enumerable.Range(1, numberOfFakes).Select(i => Fake<T>(options => optionsBuilder(options, i))).ToList();
>
> Why start at index 1? That's pretty unusual...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FakeItEasy/FakeItEasy/pull/1844#pullrequestreview-671753787>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAY7YFMPTEKIF37UFJTCHQTTQEB2FANCNFSM45XFNXWQ>
> .
>

2021-05-31 08:06 UTC, PiotrKlecha commented
@thomaslevesque Thank you for your review, I started the index at 1, because that was how it started in the example: https://github.com/FakeItEasy/FakeItEasy/issues/1838#issuecomment-846171643, so I thought it was the preferred option. But it's probably more intuitive to start at 0, so I'll change that.

@blairconrad Thank you for your review and update to docs, I don't mind at all.

2021-05-31 10:20 UTC, blairconrad commented
> @thomaslevesque Thank you for your review, I started the index at 1, because that was how it started in the example: [#1838 (comment)](https://github.com/FakeItEasy/FakeItEasy/issues/1838#issuecomment-846171643), so I thought it was the preferred option. But it's probably more intuitive to start at 0, so I'll change that.

I lead you astray with my bad example. Sorry about that!

2021-05-31 22:05 UTC, PiotrKlecha commented
> I lead you astray with my bad example. Sorry about that!

@blairconrad No problem, fortunately, it was easy to fix.

2021-05-31 22:21 UTC, thomaslevesque approved these changes
Looking great, thanks @PiotrKlecha!

@blairconrad I'm not merging yet, in case you want to review the latest changes.

2021-06-01 10:26 UTC, blairconrad approved these changes
Looks great. Thanks, @PiotrKlecha!

2021-06-01 10:26 UTC, merged