Evaluate matchers only if needed
FakeItEasy/FakeItEasy pull request #1975
Opened 2023-12-22 07:48 UTC by Miista

When evaluating whether to apply a user rule the checks have the following order:

1. IsApplicableTo
2. HasNotBeenCalledSpecifiedNumberOfTimes

This commit changes that order to:

1. HasNotBeenCalledSpecifiedNumberOfTimes
2. IsApplicableTo

This means that we only evaluate matchers if the rule has not been called the specified number of times.

2023-12-22 11:38 UTC, blairconrad commented
Hi, @Miista. Thanks for your interest.

Can you explain why you think this change is appropriate? Is it a feeling that this will be more efficient, or have you noticed some more dramatic ill effects with the current code?
Technically this is a breaking change, and wouldn't be eligible until a major release (which we can scheduled at any time, but we like to have a pretty strong reason).
In any event, we wouldn't merge the change without test changes that verified the new behaviour.

2023-12-22 14:31 UTC, thomaslevesque commented
> Technically this is a breaking change

Just to clarify what @blairconrad meant: this is a breaking change because if the argument matchers have side effects, those side effects will no longer happen if `HasNotBeenCalledSpecifiedNumberOfTimes` returns false.

(Obviously, having side effects in matchers is probably not a good idea, but we can't prevent people from doing it.)

Strictly speaking, I think this change would make sense, but we need to carefully consider the impacts. In fact, I think we might have discussed this in the past already and decided against it... I'll see if I can find something about it.

2023-12-22 15:26 UTC, jrosiek commented
Some additional context of why this PR was proposed: https://github.com/Miista/FakeItEasy.Capture/issues/1

2023-12-23 04:55 UTC, thomaslevesque commented
Hi @jrosiek,
Thanks for your comment, this is useful information. I was not aware of this project.

> I'm curious what is your stance on the argument capture functionality in general (I guess you must have had discussions about it).

As a matter of fact, [we have](https://github.com/FakeItEasy/FakeItEasy/issues/1950)! We've been struggling to find the right way to do it, and FakeItEasy.Capture has an interesting approach, although it has some limitations (e.g. no way to constrain the captured argument).

Given the way FakeItEasy.Capture works, I understand how evaluating the matchers every time could be a problem. Personally, I wouldn't mind swapping the condition. It would technically be a breaking change, but unlikely to affect many people. If we do it, and treat it as a breaking change, it means it won't be released until the next major version, which we haven't really started working on yet. And anyway, a built-in mechanism to capture argument values is something we're considering for the next major version, if we find an approach we like...

2023-12-23 05:41 UTC, Miista commented
@thomaslevesque I can find some time to look into support for constraining the captured argument.

2023-12-23 06:31 UTC, thomaslevesque commented
> I can find some time to look into support for constraining the captured argument.

Actually, I already gave it some thought. I think it would be nice to leverage the existing FakeItEasy argument constraints, so maybe it could be done like this (based on the example in your README):

```csharp
var singleArgument = new Capture<string>(that => that.StartsWith("foo"));
```

2023-12-23 07:46 UTC, Miista commented
@thomaslevesque Sure. That could be implemented pretty easily. We would pass on the `Func<T, bool>` to `A<T>`. 

You mentioned other limitations.

2023-12-23 13:17 UTC, blairconrad commented
Thanks for the additional context, @jrosiek. Indeed we have recently discussed making capturing of arguments a "first class citizen". See #1950. We'd been going down a path not completely dissimilar to FakeItEasy.Capture (which we'd never heard of until #1975 was raised) and then started veering into other territory.

I put the work on hold because I needed time to resolve my thoughts on which path was "best" (neither will be perfect) and to figure out how supporting capture from the already-recorded calls side would look. And work and family commitments kept me from having big enough blocks of time to really formulate something. I'd expected to come back by now, since my Christmas holidays started a week ago, but… life.

2023-12-23 13:54 UTC, blairconrad commented
@Miista 

> Edit: I understand there's interest for merging this PR. Is that correct?

Yes. In time. I like your change. I think it's superior to the order the checks were originally implemented. I'd merge it right now except for

1. the lack of test; if we're changing user-visible behaviour, I'd like to see something that tests that (and ensures we don't backslide), and
2. the timing. I think this should be in a major release. We have the power to schedule one whenever we want, but I don't _love_ the idea of putting 9.0.0 out right after 8.0.0. If nothing else, I'd like to see if we're going to end up with additional breaking changes due to the overall "Capture" conversation.

2023-12-23 14:34 UTC, Miista commented
@blairconrad What kind of tests did you have in mind?

I ran the tests locally both before and after making the change. 
I also added (and since removed) a test verifying that this change did indeed fix the problem mentioned in Miista/FakeItEasy.Capture#1

2023-12-23 18:28 UTC, blairconrad commented
> I also added (and since removed) a test verifying that this change did indeed fix the problem mentioned in https://github.com/Miista/FakeItEasy.Capture/issues/1

This would be the one. I'd add a test in Specs to verify that the argument constraints for an expiring call constraint aren't exercised once the maximum call count had been reached.

2023-12-23 19:02 UTC, Miista commented
@blairconrad The test was using code from Miista/FakeItEasy.Capture. Are you suggesting to add my code to FakeItEasy?

2023-12-23 20:05 UTC, blairconrad commented
I'm suggesting writing a test to exercise FakeItEasy (from the outside, as the Specs do) that will verify that the # of times a call has been triggered will short-circuit the "is applicable" check.
As @thomaslevesque recently said to me in sidechat, 

> […] the hardest part when making a change to FakeItEasy is often figuring out where to put the new specs 🤔

I don't think there's a perfect match here, but I'd consider adding the new test to either `CallMatchingSpecs` or `ThenSpecs`. The first is a little broad, and the second a little too narrow, but making a 3rd place at this time isn't something I'd ask of you. Nor am I sure we want a 3rd place…

Anyhow, if this is too onerous, I'd be willing, with your permission, to add the test to your branch.

2023-12-23 20:48 UTC, Miista commented
@blairconrad I will try to get it done within the next few days.

2023-12-23 21:16 UTC, blairconrad commented
Cool, cool @Miista. No rush.

2023-12-24 04:46 UTC, thomaslevesque commented
> You mentioned other limitations.

To be honest, I don't remember what else I had in mind 😅
Anyway, it's a bit off topic for this issue. We should continue the discussion about capturing approaches in #1950.

2023-12-31 14:14 UTC, Miista commented
@blairconrad I've added tests in CallMatchingSpecs.cs

2024-01-01 19:09 UTC, blairconrad commented
Thanks, @Miista! I eyeballed it and it will definitely ensure that the fix will stay fixed.
It did introduce a number of new style warnings, but those are hard to see right now in the middle of the security violations we have (and which I'm hoping #1982 will fix), so I am not surprised you missed them. These aren't a huge deal and there's probably no huge rush to address, since we'll eventually need to rebase the branch anyhow, and refrain from merging until we're ready for a major release…

2024-01-02 01:39 UTC, thomaslevesque approved these changes
Thanks, @Miista!
As mentioned by @blairconrad, there are a few StyleCop violations, but we can push a commit to your branch to fix them ourselves.

2024-01-02 01:39 UTC, thomaslevesque commented on tests/FakeItEasy.Specs/CallMatchingSpecs.cs
> +        public static void Test(IHaveAnIntParameter fake, List<int> results, List<int> arguments)
The name should be more descriptive.
Something like `ArgumentMatchersAreOnlyEvaluatedIfTheSpecifiedNumberOfTimesHaveBeenReached`
(yes, it's a mouthful... but at least we know what the test does)

2024-01-02 01:41 UTC, thomaslevesque commented
Actually, I didn't mean to approve yet, since at least my remark about the method name should be addressed 🤦

2024-01-02 02:51 UTC, blairconrad commented
@thomaslevesque and I have been talking. Seeing the test actually drove home to me how surprising the current code is. This fix is still a change in behaviour, but I think the current behaviour is an error, not just a different-than-expected option. I've labelled the PR a bug fix. Bug fixes often change behaviour, but don't require a major version bump.

2024-01-02 03:50 UTC, thomaslevesque commented
I pushed fixes to the branch to address my comments, and fix the StyleCop/CA warnings.

2024-01-02 16:55 UTC, blairconrad requested changes

2024-01-02 16:55 UTC, blairconrad commented on tests/FakeItEasy.Specs/CallMatchingSpecs.cs
> +            "And a argument matching predicate that records the argument and always returns true"
```suggestion
            "And an argument matching predicate that records the argument and always returns true"

```

2024-01-02 16:55 UTC, blairconrad commented on tests/FakeItEasy.Specs/CallMatchingSpecs.cs
> +                    .Equal(new[] { 0, 1 }, because: "those are the arguments used when invoking the fake"));
I never use `Equal`! Instead I use `BeEquivalentTo`, which until now I didn't realize was agnostic to the order of the collections. I have some tests to change. Thanks!

2024-01-02 16:55 UTC, blairconrad commented on tests/FakeItEasy.Specs/CallMatchingSpecs.cs
> +            "Then the arguments used in the calls are recorded only once"
```suggestion
            "Then the arguments used in the calls are recorded exactly once"
```

Or leave it. I'm not _that_ fussy.

2024-01-02 16:56 UTC, blairconrad commented
Thanks. Minor comments (the "an" is the only one I really care about). Feel free to squash/rebase/whatever.

2024-01-02 20:55 UTC, thomaslevesque commented
I amended the last commit to address your comments

2024-01-03 00:08 UTC, blairconrad approved these changes
Thanks, @thomaslevesque. Sorry, I should've been more clear. Rebasing on top of FakeItEasy/master would've also been fine. Maybe you realized this and chose not to. Whatevs!

2024-01-03 02:04 UTC, thomaslevesque commented
I didn't rebase because it's not my branch... But if you're ready to merge, I guess there's no harm. I'll do it now.

2024-01-03 02:15 UTC, merged

2024-01-03 02:16 UTC, blairconrad commented
Thanks @Miista (and @thomaslevesque for the tidying)!

2024-01-03 06:56 UTC, Miista commented
@blairconrad That's awesome. What are the next steps from here?

2024-01-03 16:31 UTC, blairconrad commented
Eventually we'll release! Since my capturing PR seems to be settling down, we're likely to wait until that's done (days not weeks). If it drags on longer, we may reconsider the release schedule.

2024-01-05 01:05 UTC, blairconrad commented
Thanks again, @Miista. Look for you name in the release notes! 

🥇